### ISSUE TITLE
fix unnamed chunk label shim

### ISSUE THREAD

**Issue by zkamvar** [carpentries/dovetail#16]
At the moment, unnamed chunk labels within our blocks are labeled as with the current time and a random 10-character string. One problem I quickly realized is that if we use this, then as people build the lessons, figures of unnamed chunks (there are a lot of them) will begin to pile up and bloat the gh-pages branch. 

There are a couple of methods for addressing this:

1. create my own counter and prepend "dovetail-chunk-n" to the unnamed chunk name
2. hijack the counter in knitr (note: [reticulate does this with the `plot_counter()`](https://github.com/rstudio/reticulate/blob/a8701771fe759161c76a8e4a81d4ccc506269de1/R/knitr-engine.R#L234)) and increment.

**Comment by fmichonneau** [comment]
maybe a more ~~annoying~~ opinionated alternative would be to require them to be named.
There is also https://github.com/lockedata/namer that might be useful.

**Comment by zkamvar** [comment]
I don't think we should be too opinionated on this for a couple of reasons:

1. it places a new burden on the contributors that is [one of the harder problems in computer science](https://www.martinfowler.com/bliki/TwoHardThings.html)
2. It requires us to develop code either way, so I would rather go with one that's least disruptive to the current process.

**Comment by zkamvar** [comment]
This is partially addressed in 4e570df9
